p=[-1,1;-1,1]	 % 输入向量有两个分量，两个分量取值范围均为-1~1
 t=1;	 
net=newp(p,t);             % 创建
 P=[0,0,1,1;0,1,0,1]        % 训练样本
 T=[0,1,1,1]	           % 目标输出  或 逻辑
 net=train(net,P,T); 
 newP=[0,0.9];             % 新的样本
 newT=sim(net,newP)    % 测试
 newP=[0.9,0.9]';	 
 newT=sim(net,newP) 
  newT=sim(net,P) 
